# 20820A1 firmware build 295
# patch entries used: 34 out of 256 elf patches, 13%
CY_PATCH_ENTRIES_BASE=34
# additional patch entries in these libraries:
#   23 in mpaf_lib.a
#   3 in wiced_blurtooth_lib.a
#   2 in mesh_optimized_continuous_scan_lib.a
#   7 in ble_antenna_diversity_lib.a
#   11 in modus_peps_lib.a
#   1 in dbfw_lib.a
#   49 in bt_lib.a
#   13 in modus_lesniff_sensor_lib.a
#   28 in foundation_lib.a
#   7 in modus_peps_sensor_overble_lib.a
#   4 in wiced_uart_raw_mode_lib.a
#   2 in wiced_hidd_lib.a
#   41 in certification_lib.a
#   8 in modus_peps_overble_lib.a
#   5 in modus_lesniff_lib.a
#   1 in wiced_bt_ble_lib.a
#   5 in wiced_external_pa_lib.a
#   7 in multi_adv_lib.a
#   6 in wiced_rf_lib.a
#   4 in wiced_audio_source_lib.a
#   13 in modus_peps_sensor_lib.a
#   2 in cfa_mm_alloc_free_replace_lib.a
#   1 in adva_lib.a
#   4 in wiced_hal_lib.a
#   12 in wiced_ble_connect_timing_lib.a
# patch ram used: 3416 out of 15360 bytes, 22%
