# 20820A1 firmware build 230
# patch entries used: 88 out of 256 elf patches, 34%
CY_PATCH_ENTRIES_BASE=88
# additional patch entries in these libraries:
#   7 in modus_peps_overble_lib.a
#   7 in modus_peps_sensor_overble_lib.a
#   8 in wiced_ble_connect_timing_lib.a
#   3 in modus_peps_lib.a
#   1 in dbfw_lib.a
#   1 in wiced_hidd_lib.a
#   7 in multi_adv_lib.a
#   2 in mesh_optimized_continuous_scan_lib.a
#   4 in wiced_uart_raw_mode_lib.a
#   7 in modus_peps_sensor_lib.a
#   4 in wiced_audio_source_lib.a
#   2 in cfa_mm_alloc_free_replace_lib.a
#   6 in mpaf_lib.a
# patch ram used: 14752 out of 15360 bytes, 96%
